Repository sky-uk/clusterverse, pull requests merged in 2020-02, with the labels that each got.

#23 Fix Route53 deletion with private zones
  clean/tasks/main.yml
Labels: bug

#24 [FIX] Add region args as required and convert owner label to lowercase
  create/tasks/aws.yml
  create/tasks/gce.yml
Labels: bug

#29 [DOCS] Canary variable mandatory for redeploy invocation
  EXAMPLE/README.md
Labels: documentation

#26 [FEATURE] Add Cloud DNS automation for GCP A/CNAME records
  EXAMPLE/group_vars/test_gce_euw1/cluster_vars.yml
  clean/tasks/gce.yml
  config/tasks/main.yml
  dynamic_inventory/tasks/main.yml
Labels: enhancement

#34 [FEATURE] Centos support init
  EXAMPLE/group_vars/test_aws_euw1/cluster_vars.yml
  config/tasks/cloud_agents.yml
  config/tasks/disks_auto.yml
  config/tasks/disks_auto_aws_nvme.yml
  config/tasks/filebeat.yml
Labels: enhancement
